import type { Question, Lesson, StudyTask } from "./types";

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: "q1",
    text: "\\log_2 8 = ?",
    options: ["2", "3", "4", "1"],
    answer: "3",
    solution: "\\log_2 8 = \\log_2 2^3 = 3",
    topic: "Logarifm",
    difficulty: "Oson",
    examType: ["DTM", "Milliy Sertifikat"],
  },
  {
    id: "q2",
    text: "\\int_0^1 x^2 \\, dx = ?",
    options: ["\\frac{1}{2}", "\\frac{1}{3}", "\\frac{1}{4}", "1"],
    answer: "\\frac{1}{3}",
    solution: "\\int_0^1 x^2 dx = \\left[\\frac{x^3}{3}\\right]_0^1 = \\frac{1}{3}",
    topic: "Integral",
    difficulty: "O'rtacha",
    examType: ["DTM"],
  },
  {
    id: "q3",
    text: "\\sin^2 x + \\cos^2 x = ?",
    options: ["0", "2", "1", "-1"],
    answer: "1",
    solution: "\\text{Bu trigonometriyaning asosiy formulasi}",
    topic: "Trigonometriya",
    difficulty: "Oson",
    examType: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "q4",
    text: "f(x) = x^3 \\text{ bo'lsa, } f'(x) = ?",
    options: ["x^2", "3x^2", "3x", "2x^3"],
    answer: "3x^2",
    solution: "f'(x) = (x^3)' = 3x^2",
    topic: "Hosila",
    difficulty: "Oson",
    examType: ["DTM", "Maktab"],
  },
  {
    id: "q5",
    text: "2x + 5 = 13 \\text{ tenglamani yeching}",
    options: ["x=3", "x=4", "x=5", "x=6"],
    answer: "x=4",
    solution: "2x = 13 - 5 = 8 \\Rightarrow x = 4",
    topic: "Algebra",
    difficulty: "Oson",
    examType: ["Maktab"],
  },
  {
    id: "q6",
    text: "\\text{To'g'ri burchakli uchburchakda } a=3, b=4 \\text{ bo'lsa, } c=?",
    options: ["5", "6", "7", "8"],
    answer: "5",
    solution: "c = \\sqrt{a^2 + b^2} = \\sqrt{9+16} = \\sqrt{25} = 5",
    topic: "Geometriya",
    difficulty: "Oson",
    examType: ["DTM", "Maktab"],
  },
  {
    id: "q7",
    text: "1, 4, 9, 16, 25, \\ldots \\text{ ketma-ketlikning 7-hadi?}",
    options: ["36", "49", "64", "81"],
    answer: "49",
    solution: "a_n = n^2, \\quad a_7 = 7^2 = 49",
    topic: "Ketma-ketlik",
    difficulty: "Oson",
    examType: ["DTM", "Milliy Sertifikat"],
  },
  {
    id: "q8",
    text: "C_5^2 = ?",
    options: ["10", "15", "20", "5"],
    answer: "10",
    solution: "C_5^2 = \\frac{5!}{2! \\cdot 3!} = \\frac{20}{2} = 10",
    topic: "Kombinatorika",
    difficulty: "O'rtacha",
    examType: ["DTM"],
  },
];

export const SAMPLE_LESSONS: Lesson[] = [
  {
    id: "l1",
    title: "Logarifm asoslari",
    topic: "Logarifm",
    duration: "45 min",
    description: "Logarifm ta'rifi, xossalari va misollari",
    isPremium: false,
  },
  {
    id: "l2",
    title: "Aniq integral",
    topic: "Integral",
    duration: "60 min",
    description: "Newton-Leybnits formulasi va qo'llanilishi",
    isPremium: true,
  },
  {
    id: "l3",
    title: "Trigonometrik formulalar",
    topic: "Trigonometriya",
    duration: "50 min",
    description: "Asosiy trigonometrik identikliklar",
    isPremium: false,
  },
  {
    id: "l4",
    title: "Hosila va qo'llanilishi",
    topic: "Hosila",
    duration: "55 min",
    description: "Hosilaning geometrik ma'nosi va hisoblash",
    isPremium: false,
  },
  {
    id: "l5",
    title: "Kombinatorika",
    topic: "Kombinatorika",
    duration: "40 min",
    description: "Permutatsiya, kombinatsiya va joylashma",
    isPremium: true,
  },
  {
    id: "l6",
    title: "Arifmetik ketma-ketlik",
    topic: "Ketma-ketlik",
    duration: "35 min",
    description: "Arifmetik va geometrik progressiya",
    isPremium: false,
  },
];

export const SAMPLE_STUDY_TASKS: StudyTask[] = [
  { id: "t1", title: "Logarifm mashqlari", subject: "Matematika", duration: "30 min", done: false },
  { id: "t2", title: "Integral takrorlash", subject: "Matematika", duration: "45 min", done: true },
  { id: "t3", title: "DTM test ishlash", subject: "Amaliyot", duration: "60 min", done: false },
];