import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://cngkzlkreddsdpjqflsb.supabase.co",
  "sb_publishable_XBtykx-ZbWc1326el4G5SA_JEgpuDOo"
);

const questions = [
  {
    id: "geo_001",
    text: "O'tkir burchakning $\\sin \\alpha = \\dfrac{3}{5}$. $\\cos \\alpha$ ni toping.",
    options: ["$\\dfrac{4}{5}$", "$\\dfrac{3}{4}$", "$\\dfrac{5}{4}$", "$\\dfrac{2}{5}$"],
    answer: "$\\dfrac{4}{5}$",
    solution: "$\\cos \\alpha = \\sqrt{1 - \\sin^2 \\alpha} = \\sqrt{\\dfrac{16}{25}} = \\dfrac{4}{5}$",
    topic: "Trigonometriya",
    difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_002",
    text: "O'tkir burchakning $\\cos \\alpha = \\dfrac{5}{13}$. $\\sin \\alpha$ ni toping.",
    options: ["$\\dfrac{12}{13}$", "$\\dfrac{8}{13}$", "$\\dfrac{5}{12}$", "$\\dfrac{7}{13}$"],
    answer: "$\\dfrac{12}{13}$",
    solution: "$\\sin \\alpha = \\sqrt{1 - \\dfrac{25}{169}} = \\dfrac{12}{13}$",
    topic: "Trigonometriya",
    difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_003",
    text: "O'tkir burchakning $\\sin \\alpha = \\dfrac{7}{25}$. $\\tg \\alpha$ ni toping.",
    options: ["$\\dfrac{7}{24}$", "$\\dfrac{7}{25}$", "$\\dfrac{24}{7}$", "$\\dfrac{25}{24}$"],
    answer: "$\\dfrac{7}{24}$",
    solution: "$\\cos \\alpha = \\dfrac{24}{25}$; $\\quad \\tg \\alpha = \\dfrac{7/25}{24/25} = \\dfrac{7}{24}$",
    topic: "Trigonometriya",
    difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_004",
    text: "O'tkir burchakning $\\cos \\alpha = \\dfrac{15}{17}$. $\\tg \\alpha$ ni toping.",
    options: ["$\\dfrac{8}{15}$", "$\\dfrac{8}{17}$", "$\\dfrac{15}{8}$", "$\\dfrac{17}{8}$"],
    answer: "$\\dfrac{8}{15}$",
    solution: "$\\sin \\alpha = \\dfrac{8}{17}$; $\\quad \\tg \\alpha = \\dfrac{8}{15}$",
    topic: "Trigonometriya",
    difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_005",
    text: "O'tmas burchakning $\\sin \\alpha = 0{,}6$. $\\cos \\alpha$ ni toping.",
    options: ["-0,8", "0,8", "-0,4", "0,4"],
    answer: "-0,8",
    solution: "$90° < \\alpha < 180°$ da $\\cos \\alpha < 0$. $\\cos \\alpha = -\\sqrt{1-0{,}36} = -0{,}8$",
    topic: "Trigonometriya",
    difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_006",
    text: "O'tmas burchakning $\\cos \\alpha = -\\dfrac{24}{25}$. $\\sin \\alpha$ ni toping.",
    options: ["$\\dfrac{7}{25}$", "$-\\dfrac{7}{25}$", "$\\dfrac{24}{25}$", "$\\dfrac{1}{25}$"],
    answer: "$\\dfrac{7}{25}$",
    solution: "$\\sin \\alpha = \\sqrt{1 - \\dfrac{576}{625}} = \\dfrac{7}{25}$",
    topic: "Trigonometriya",
    difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_007",
    text: "O'tmas burchakning $\\cos \\alpha = -\\dfrac{5}{13}$. $\\tg \\alpha$ ni toping.",
    options: ["$-\\dfrac{12}{5}$", "$\\dfrac{12}{5}$", "$-\\dfrac{5}{12}$", "$\\dfrac{13}{5}$"],
    answer: "$-\\dfrac{12}{5}$",
    solution: "$\\sin \\alpha = \\dfrac{12}{13}$; $\\quad \\tg \\alpha = \\dfrac{12/13}{-5/13} = -\\dfrac{12}{5}$",
    topic: "Trigonometriya",
    difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_008",
    text: "Qo'shni burchaklardan biri $47°$ ga teng. Ikkinchi burchakni toping.",
    options: ["$133°$", "$43°$", "$143°$", "$53°$"],
    answer: "$133°$",
    solution: "$\\beta = 180° - 47° = 133°$",
    topic: "Geometriya",
    difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_009",
    text: "O'tmas burchak $130°$ ga teng. Unga qo'shni burchakni toping.",
    options: ["$50°$", "$40°$", "$60°$", "$130°$"],
    answer: "$50°$",
    solution: "$\\beta = 180° - 130° = 50°$",
    topic: "Geometriya",
    difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_010",
    text: "Qo'shni burchaklardan biri ikkinchisidan $60°$ ga katta. O'tkir burchakni toping.",
    options: ["$60°$", "$70°$", "$30°$", "$120°$"],
    answer: "$60°$",
    solution: "$\\alpha + (\\alpha + 60°) = 180° \\Rightarrow 2\\alpha = 120° \\Rightarrow \\alpha = 60°$",
    topic: "Geometriya",
    difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_011",
    text: "Qo'shni burchaklardan biri ikkinchisidan $72°$ ga katta. O'tkir burchakni toping.",
    options: ["$54°$", "$36°$", "$72°$", "$64°$"],
    answer: "$54°$",
    solution: "$2\\alpha + 72° = 180° \\Rightarrow \\alpha = 54°$",
    topic: "Geometriya",
    difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_012",
    text: "Qo'shni burchaklar $2:7$ nisbatda. Shu burchaklarni toping.",
    options: ["$40°$ va $140°$", "$36°$ va $144°$", "$45°$ va $135°$", "$20°$ va $160°$"],
    answer: "$40°$ va $140°$",
    solution: "$9x = 180° \\Rightarrow x = 20°$; $\\quad \\alpha = 40°$, $\\beta = 140°$",
    topic: "Geometriya",
    difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_013",
    text: "Qo'shni burchaklar $4:5$ nisbatda. Shu burchaklarni toping.",
    options: ["$80°$ va $100°$", "$72°$ va $108°$", "$40°$ va $140°$", "$90°$ va $90°$"],
    answer: "$80°$ va $100°$",
    solution: "$9x = 180° \\Rightarrow x = 20°$; $\\quad \\alpha = 80°$, $\\beta = 100°$",
    topic: "Geometriya",
    difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_014",
    text: "Qo'shni burchaklardan biri ikkinchisidan $3$ marta katta. Shu burchaklarni toping.",
    options: ["$45°$ va $135°$", "$30°$ va $150°$", "$60°$ va $120°$", "$40°$ va $140°$"],
    answer: "$45°$ va $135°$",
    solution: "$4\\alpha = 180° \\Rightarrow \\alpha = 45°$, $\\beta = 135°$",
    topic: "Geometriya",
    difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_015",
    text: "Ikki to'g'ri chiziq kesishishidan hosil bo'lgan burchaklardan uchtasining yig'indisi $300°$. O'tkir burchakni toping.",
    options: ["$60°$", "$80°$", "$70°$", "$50°$"],
    answer: "$60°$",
    solution: "$\\alpha + 2\\beta = 300°$, $\\alpha + \\beta = 180° \\Rightarrow \\beta = 120°$, $\\alpha = 60°$",
    topic: "Geometriya",
    difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
];

const { data, error } = await supabase.from("questions").upsert(questions);

if (error) {
  console.error("Xato:", error.message);
} else {
  console.log(`✓ ${questions.length} ta masala muvaffaqiyatli yuklandi!`);
}
