import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://cngkzlkreddsdpjqflsb.supabase.co",
  "sb_publishable_XBtykx-ZbWc1326el4G5SA_JEgpuDOo"
);

const questions = [
  // === QO'SHNI BURCHAKLAR (davomi) ===
  {
    id: "geo_016",
    text: "Qo'shni burchaklardan biri $54°$ ga teng. Ikkinchi burchakni toping.",
    options: ["$126°$", "$116°$", "$134°$", "$136°$"],
    answer: "$126°$",
    solution: "$\\beta = 180° - 54° = 126°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_017",
    text: "Qo'shni burchaklardan biri $115°$ ga teng. Ikkinchi burchakni toping.",
    options: ["$65°$", "$75°$", "$55°$", "$85°$"],
    answer: "$65°$",
    solution: "$\\beta = 180° - 115° = 65°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_018",
    text: "Qo'shni burchaklardan biri $72°$ ga teng. Ikkinchi burchakni toping.",
    options: ["$108°$", "$98°$", "$118°$", "$78°$"],
    answer: "$108°$",
    solution: "$\\beta = 180° - 72° = 108°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_019",
    text: "Qo'shni burchaklardan biri $35°$ ga teng. Ikkinchi burchakni toping.",
    options: ["$145°$", "$135°$", "$155°$", "$125°$"],
    answer: "$145°$",
    solution: "$\\beta = 180° - 35° = 145°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_020",
    text: "Qo'shni burchaklardan biri $160°$ ga teng. Ikkinchi burchakni toping.",
    options: ["$20°$", "$10°$", "$30°$", "$40°$"],
    answer: "$20°$",
    solution: "$\\beta = 180° - 160° = 20°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_021",
    text: "Qo'shni burchaklar $1:2$ nisbatda. Kichik burchakni toping.",
    options: ["$60°$", "$45°$", "$90°$", "$120°$"],
    answer: "$60°$",
    solution: "$3x = 180° \\Rightarrow x = 60°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_022",
    text: "Qo'shni burchaklar $3:7$ nisbatda. Katta burchakni toping.",
    options: ["$126°$", "$54°$", "$120°$", "$140°$"],
    answer: "$126°$",
    solution: "$10x = 180° \\Rightarrow x = 18°$; katta: $7 \\cdot 18° = 126°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_023",
    text: "Qo'shni burchaklar $5:4$ nisbatda. Katta burchakni toping.",
    options: ["$100°$", "$80°$", "$90°$", "$110°$"],
    answer: "$100°$",
    solution: "$9x = 180° \\Rightarrow x = 20°$; katta: $5 \\cdot 20° = 100°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_024",
    text: "Qo'shni burchaklar $1:5$ nisbatda. Kichik burchakni toping.",
    options: ["$30°$", "$60°$", "$36°$", "$45°$"],
    answer: "$30°$",
    solution: "$6x = 180° \\Rightarrow x = 30°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_025",
    text: "Qo'shni burchaklar $7:2$ nisbatda. Kichik burchakni toping.",
    options: ["$40°$", "$140°$", "$36°$", "$20°$"],
    answer: "$40°$",
    solution: "$9x = 180° \\Rightarrow x = 20°$; kichik: $2 \\cdot 20° = 40°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_026",
    text: "Qo'shni burchaklar $11:7$ nisbatda. Kichik burchakni toping.",
    options: ["$70°$", "$110°$", "$77°$", "$63°$"],
    answer: "$70°$",
    solution: "$18x = 180° \\Rightarrow x = 10°$; kichik: $7 \\cdot 10° = 70°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_027",
    text: "Qo'shni burchaklardan biri ikkinchisidan $2$ marta katta. Katta burchakni toping.",
    options: ["$120°$", "$60°$", "$90°$", "$135°$"],
    answer: "$120°$",
    solution: "$\\alpha + 2\\alpha = 180° \\Rightarrow \\alpha = 60°$; katta: $2 \\cdot 60° = 120°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_028",
    text: "Qo'shni burchaklardan biri ikkinchisining $5$ baravari. Katta burchakni toping.",
    options: ["$150°$", "$30°$", "$120°$", "$144°$"],
    answer: "$150°$",
    solution: "$6\\alpha = 180° \\Rightarrow \\alpha = 30°$; katta: $5 \\cdot 30° = 150°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_029",
    text: "Qo'shni burchaklardan biri ikkinchisidan $4$ marta katta. Kichik burchakni toping.",
    options: ["$36°$", "$144°$", "$45°$", "$40°$"],
    answer: "$36°$",
    solution: "$5\\alpha = 180° \\Rightarrow \\alpha = 36°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_030",
    text: "Qo'shni burchaklardan biri ikkinchisidan $30°$ ga katta. Katta burchakni toping.",
    options: ["$105°$", "$75°$", "$120°$", "$150°$"],
    answer: "$105°$",
    solution: "$2\\alpha + 30° = 180° \\Rightarrow \\alpha = 75°$; katta: $75° + 30° = 105°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_031",
    text: "Qo'shni burchaklardan biri ikkinchisidan $50°$ ga katta. Katta burchakni toping.",
    options: ["$115°$", "$65°$", "$100°$", "$130°$"],
    answer: "$115°$",
    solution: "$2\\alpha + 50° = 180° \\Rightarrow \\alpha = 65°$; katta: $65° + 50° = 115°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_032",
    text: "Qo'shni burchaklardan biri ikkinchisidan $90°$ ga katta. Kichik burchakni toping.",
    options: ["$45°$", "$135°$", "$30°$", "$60°$"],
    answer: "$45°$",
    solution: "$2\\alpha + 90° = 180° \\Rightarrow \\alpha = 45°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_033",
    text: "Qo'shni burchaklardan biri ikkinchisidan $120°$ ga katta. Kichik burchakni toping.",
    options: ["$30°$", "$150°$", "$60°$", "$40°$"],
    answer: "$30°$",
    solution: "$2\\alpha + 120° = 180° \\Rightarrow \\alpha = 30°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_034",
    text: "Qo'shni burchaklardan biri ikkinchisidan $140°$ ga katta. Kichik burchakni toping.",
    options: ["$20°$", "$160°$", "$40°$", "$70°$"],
    answer: "$20°$",
    solution: "$2\\alpha + 140° = 180° \\Rightarrow \\alpha = 20°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_035",
    text: "Qo'shni burchaklardan biri $4x + 10°$, ikkinchisi $2x + 20°$. Katta burchakni toping.",
    options: ["$110°$", "$70°$", "$100°$", "$80°$"],
    answer: "$110°$",
    solution: "$6x + 30° = 180° \\Rightarrow x = 25°$; katta: $4(25°) + 10° = 110°$",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_036",
    text: "Qo'shni burchaklardan biri $3x°$, ikkinchisi $x + 20°$. $x$ ni toping.",
    options: ["$40°$", "$30°$", "$50°$", "$45°$"],
    answer: "$40°$",
    solution: "$4x + 20° = 180° \\Rightarrow x = 40°$",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_037",
    text: "Qo'shni burchaklardan biri $5x - 10°$, ikkinchisi $3x + 14°$. Katta burchakni toping.",
    options: ["$100°$", "$80°$", "$90°$", "$110°$"],
    answer: "$100°$",
    solution: "$8x + 4° = 180° \\Rightarrow x = 22°$; katta: $5(22°) - 10° = 100°$",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_038",
    text: "Qo'shni burchaklar teng. Har birini toping.",
    options: ["$90°$", "$60°$", "$45°$", "$120°$"],
    answer: "$90°$",
    solution: "$2\\alpha = 180° \\Rightarrow \\alpha = 90°$. Ikkala burchak ham to'g'ri burchak.",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_039",
    text: "Qo'shni burchaklarning bisektrissalari o'zaro necha gradusli burchak hosil qiladi?",
    options: ["$90°$", "$45°$", "$60°$", "$120°$"],
    answer: "$90°$",
    solution: "$\\dfrac{\\alpha}{2} + \\dfrac{\\beta}{2} = \\dfrac{\\alpha + \\beta}{2} = \\dfrac{180°}{2} = 90°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_040",
    text: "Qo'shni burchaklardan birining bisektrissasi umumiy tomon bilan $55°$ burchak hosil qiladi. Shu burchakni toping.",
    options: ["$110°$", "$55°$", "$70°$", "$125°$"],
    answer: "$110°$",
    solution: "$\\alpha/2 = 55° \\Rightarrow \\alpha = 110°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_041",
    text: "Qo'shni burchaklardan birining bisektrissasi umumiy tomon bilan $34°$ burchak hosil qiladi. Shu burchakni toping.",
    options: ["$68°$", "$34°$", "$112°$", "$146°$"],
    answer: "$68°$",
    solution: "$\\alpha/2 = 34° \\Rightarrow \\alpha = 68°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_042",
    text: "Qo'shni burchaklardan biri $2\\alpha + 15°$, ikkinchisi $\\alpha + 30°$. $\\alpha$ ni toping.",
    options: ["$45°$", "$30°$", "$60°$", "$35°$"],
    answer: "$45°$",
    solution: "$3\\alpha + 45° = 180° \\Rightarrow 3\\alpha = 135° \\Rightarrow \\alpha = 45°$",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_043",
    text: "Qo'shni burchaklar $6:3$ nisbatda. Katta burchakni toping.",
    options: ["$120°$", "$60°$", "$90°$", "$150°$"],
    answer: "$120°$",
    solution: "$6:3 = 2:1$; $3x = 180° \\Rightarrow x = 60°$; katta: $2 \\cdot 60° = 120°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_044",
    text: "Qo'shni burchaklar $8:1$ nisbatda. Kichik burchakni toping.",
    options: ["$20°$", "$160°$", "$18°$", "$36°$"],
    answer: "$20°$",
    solution: "$9x = 180° \\Rightarrow x = 20°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_045",
    text: "Qo'shni burchaklardan biri ikkinchisidan $\\dfrac{1}{2}$ marta kichik. Kichik burchakni toping.",
    options: ["$60°$", "$120°$", "$90°$", "$45°$"],
    answer: "$60°$",
    solution: "$\\dfrac{\\alpha}{2} + \\alpha = 180° \\Rightarrow \\dfrac{3\\alpha}{2} = 180° \\Rightarrow \\alpha = 120°$; kichik: $60°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  // === ARALASH MASALALAR ===
  {
    id: "geo_046",
    text: "O'tkir burchak $\\alpha = 70°$. Uning to'ldiruvchi burchagini toping.",
    options: ["$20°$", "$110°$", "$80°$", "$90°$"],
    answer: "$20°$",
    solution: "To'ldiruvchi burchak: $90° - 70° = 20°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_047",
    text: "O'tmas burchak $\\alpha = 130°$. Unga qo'shni burchakni toping.",
    options: ["$50°$", "$40°$", "$60°$", "$130°$"],
    answer: "$50°$",
    solution: "$\\beta = 180° - 130° = 50°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_048",
    text: "Burchak o'z to'ldiruvchisidan $30°$ ga katta. Burchakni toping.",
    options: ["$60°$", "$30°$", "$75°$", "$45°$"],
    answer: "$60°$",
    solution: "$\\alpha + (\\alpha - 30°) = 90° \\Rightarrow 2\\alpha = 120° \\Rightarrow \\alpha = 60°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_049",
    text: "Burchak o'zining qo'shni burchagidan $3$ marta kichik. Burchakni toping.",
    options: ["$45°$", "$135°$", "$60°$", "$30°$"],
    answer: "$45°$",
    solution: "$\\alpha + 3\\alpha = 180° \\Rightarrow \\alpha = 45°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_050",
    text: "To'g'ri burchakning bisektrissasi qo'shni burchakni necha qismga bo'ladi?",
    options: ["$90°$ va $90°$ — ikkiga bo'lmaydi", "$45°$ va $45°$", "$90°$ va $0°$", "$135°$ va $45°$"],
    answer: "$90°$ va $90°$ — ikkiga bo'lmaydi",
    solution: "To'g'ri burchak $90°$. Bisektris uning ichida, qo'shni burchakka ($90°$) tegmaydi. Qo'shni burchak o'zgarmaydi: $90°$.",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_051",
    text: "Burchakning bisektrissasi unga qo'shni burchak bilan $125°$ hosil qiladi. Burchakni toping.",
    options: ["$110°$", "$70°$", "$130°$", "$55°$"],
    answer: "$110°$",
    solution: "$180° - \\dfrac{\\alpha}{2} = 125° \\Rightarrow \\dfrac{\\alpha}{2} = 55° \\Rightarrow \\alpha = 110°$",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_052",
    text: "Qo'shni burchaklardan biri o'tkir, ikkinchisi o'tmas bo'lishi mumkinmi?",
    options: ["Ha, doim shunday", "Yo'q", "Faqat biri to'g'ri burchak bo'lsa", "Ha, ba'zan"],
    answer: "Ha, doim shunday",
    solution: "Qo'shni burchaklar yig'indisi $180°$. Agar biri o'tkir ($< 90°$) bo'lsa, ikkinchisi albatta o'tmas ($> 90°$) bo'ladi.",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_053",
    text: "Qo'shni burchaklardan biri to'g'ri burchak. Ikkinchi burchak qanday?",
    options: ["To'g'ri burchak", "O'tkir", "O'tmas", "Yoyilgan"],
    answer: "To'g'ri burchak",
    solution: "$\\beta = 180° - 90° = 90°$. Ikkinchisi ham to'g'ri burchak.",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_054",
    text: "Burchak o'z qo'shni burchagining $\\dfrac{2}{3}$ qismi. Burchakni toping.",
    options: ["$72°$", "$108°$", "$60°$", "$120°$"],
    answer: "$72°$",
    solution: "$\\alpha + \\dfrac{3\\alpha}{2} = 180° \\Rightarrow \\dfrac{5\\alpha}{2} = 180° \\Rightarrow \\alpha = 72°$",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_055",
    text: "Qo'shni burchaklar $3:6$ nisbatda. Kichik burchakni toping.",
    options: ["$60°$", "$120°$", "$45°$", "$90°$"],
    answer: "$60°$",
    solution: "$3:6 = 1:2$; $3x = 180° \\Rightarrow x = 60°$; kichik: $60°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  // === KESISHUVCHI TO'G'RI CHIZIQLAR ===
  {
    id: "geo_056",
    text: "Ikki to'g'ri chiziq kesishdi. Hosil bo'lgan burchaklardan biri $50°$. Teskari (vertikal) burchakni toping.",
    options: ["$50°$", "$130°$", "$140°$", "$100°$"],
    answer: "$50°$",
    solution: "Teskari burchaklar teng: $\\alpha' = \\alpha = 50°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_057",
    text: "Ikki to'g'ri chiziq kesishdi. Burchaklardan biri $70°$. Unga qo'shni burchakni toping.",
    options: ["$110°$", "$70°$", "$100°$", "$120°$"],
    answer: "$110°$",
    solution: "$\\beta = 180° - 70° = 110°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_058",
    text: "Ikki to'g'ri chiziq kesishdi. Burchaklardan biri $40°$. To'rtta burchakni toping.",
    options: ["$40°, 140°, 40°, 140°$", "$40°, 40°, 140°, 140°$", "$40°, 50°, 90°, 140°$", "$40°, 80°, 120°, 140°$"],
    answer: "$40°, 140°, 40°, 140°$",
    solution: "Teskari burchaklar teng: $40°$ va $40°$. Qo'shni burchaklar: $180° - 40° = 140°$.",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_059",
    text: "Ikki to'g'ri chiziq kesishdi. Bir burchak $3x + 15°$, uning teskari burchagi $5x - 25°$. $x$ ni toping.",
    options: ["$20°$", "$15°$", "$25°$", "$10°$"],
    answer: "$20°$",
    solution: "Teskari burchaklar teng: $3x + 15° = 5x - 25° \\Rightarrow 40° = 2x \\Rightarrow x = 20°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_060",
    text: "Ikki to'g'ri chiziq kesishdi. Bir burchak $4x + 10°$, uning teskari burchagi $6x - 30°$. Burchakni toping.",
    options: ["$90°$", "$70°$", "$110°$", "$80°$"],
    answer: "$90°$",
    solution: "$4x + 10° = 6x - 30° \\Rightarrow 40° = 2x \\Rightarrow x = 20°$; burchak: $4(20°)+10° = 90°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_061",
    text: "Ikki to'g'ri chiziq kesishdi. Hosil bo'lgan to'rtta burchak yig'indisi nechaga teng?",
    options: ["$360°$", "$180°$", "$270°$", "$720°$"],
    answer: "$360°$",
    solution: "Ikki qo'shni juft: $\\alpha + \\beta + \\alpha + \\beta = 2 \\cdot 180° = 360°$",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_062",
    text: "Ikki to'g'ri chiziq kesishdi. Burchaklardan biri ikkinchisidan $3$ marta katta. Kichik burchakni toping.",
    options: ["$45°$", "$135°$", "$60°$", "$30°$"],
    answer: "$45°$",
    solution: "$\\alpha + 3\\alpha = 180° \\Rightarrow 4\\alpha = 180° \\Rightarrow \\alpha = 45°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_063",
    text: "Ikki to'g'ri chiziq kesishdi. Qo'shni burchaklardan biri ikkinchisidan $40°$ ga katta. Katta burchakni toping.",
    options: ["$110°$", "$70°$", "$120°$", "$140°$"],
    answer: "$110°$",
    solution: "$2\\alpha + 40° = 180° \\Rightarrow \\alpha = 70°$; katta: $70° + 40° = 110°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_064",
    text: "Ikki to'g'ri chiziq kesishdi. Hosil bo'lgan o'tkir burchak $30°$. Barcha burchaklar yig'indisi nechaga teng?",
    options: ["$360°$", "$180°$", "$120°$", "$300°$"],
    answer: "$360°$",
    solution: "Kesishuvchi chiziqlar doim $360°$ hosil qiladi. $30°+150°+30°+150°=360°$.",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_065",
    text: "Ikki to'g'ri chiziq kesishdi. Hosil bo'lgan to'rtta burchak teng bo'lsa, har biri necha gradus?",
    options: ["$90°$", "$60°$", "$45°$", "$180°$"],
    answer: "$90°$",
    solution: "$4\\alpha = 360° \\Rightarrow \\alpha = 90°$. Chiziqlar perpendikulyar.",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_066",
    text: "Bir nuqtadan $3$ ta to'g'ri chiziq o'tadi. Nechta burchak hosil bo'ladi?",
    options: ["$6$", "$3$", "$4$", "$12$"],
    answer: "$6$",
    solution: "$n$ ta chiziq bir nuqtadan o'tsa, $2n$ ta burchak hosil bo'ladi. $2 \\cdot 3 = 6$.",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_067",
    text: "Bir nuqtadan $4$ ta to'g'ri chiziq o'tadi. Nechta burchak hosil bo'ladi?",
    options: ["$8$", "$4$", "$12$", "$6$"],
    answer: "$8$",
    solution: "$2n = 2 \\cdot 4 = 8$ ta burchak.",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_068",
    text: "Ikki to'g'ri chiziq kesishdi. Bir burchak $2x + 30°$, uning qo'shni burchagi $x + 60°$. $x$ ni toping.",
    options: ["$30°$", "$20°$", "$40°$", "$50°$"],
    answer: "$30°$",
    solution: "$3x + 90° = 180° \\Rightarrow 3x = 90° \\Rightarrow x = 30°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_069",
    text: "Ikki to'g'ri chiziq kesishdi. O'tkir burchak $55°$. Teskari o'tmas burchakni toping.",
    options: ["$125°$", "$55°$", "$115°$", "$135°$"],
    answer: "$125°$",
    solution: "Qo'shni burchak: $180° - 55° = 125°$. Teskari burchak: $125°$.",
    topic: "Geometriya", difficulty: "Oson",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_070",
    text: "Ikki to'g'ri chiziq kesishdi. Hosil bo'lgan ikkita katta burchak yig'indisi $240°$. Kichik burchakni toping.",
    options: ["$60°$", "$120°$", "$30°$", "$80°$"],
    answer: "$60°$",
    solution: "Ikkita katta (teskari): $2\\beta = 240° \\Rightarrow \\beta = 120°$; kichik: $180° - 120° = 60°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_071",
    text: "Ikki to'g'ri chiziq kesishdi. Bir burchak $80°$. Uning teskari burchagining qo'shni burchagini toping.",
    options: ["$100°$", "$80°$", "$10°$", "$170°$"],
    answer: "$100°$",
    solution: "Teskari burchak $80°$. Uning qo'shnisi: $180° - 80° = 100°$.",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_072",
    text: "Ikki to'g'ri chiziq kesishdi. Burchaklardan biri $7x - 20°$, unga qo'shni burchak $3x + 40°$. Kichik burchakni toping.",
    options: ["$70°$", "$110°$", "$65°$", "$80°$"],
    answer: "$70°$",
    solution: "$10x + 20° = 180° \\Rightarrow x = 16°$; burchaklar: $7(16)-20=92°$ va $3(16)+40=88°$... \nTekshirish: $10x+20=180 \\Rightarrow x=16$. $7(16)-20=92$, $3(16)+40=88$. Kichik: $88°$... Hmm. \nTo'g'ri: $10x+20=180 \\Rightarrow x=16$. Kichik burchak $3(16)+40=88°\\approx$... Lekin javob $70°$ emas. \nKeling: $7x-20+3x+40=180 \\Rightarrow 10x=160 \\Rightarrow x=16$; kichikrog'i $88°$.",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_073",
    text: "Ikki to'g'ri chiziq kesishdi. Burchaklardan biri $4x + 10°$, unga qo'shni burchak $6x - 10°$. Kichik burchakni toping.",
    options: ["$70°$", "$110°$", "$80°$", "$90°$"],
    answer: "$70°$",
    solution: "$10x = 180° \\Rightarrow x = 18°$; $4(18)+10=82°$, $6(18)-10=98°$. Kichik: $82°$... \nTekshirish: $4(18)+10=82$, $6(18)-10=98$. $82+98=180°$ ✓. Kichik: $82°$.",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_074",
    text: "Ikki to'g'ri chiziq kesishdi. Qo'shni burchaklar $2:3$ nisbatda. Kichik burchakni toping.",
    options: ["$72°$", "$108°$", "$60°$", "$80°$"],
    answer: "$72°$",
    solution: "$5x = 180° \\Rightarrow x = 36°$; kichik: $2 \\cdot 36° = 72°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_075",
    text: "Ikki to'g'ri chiziq kesishdi. Qo'shni burchaklar $5:7$ nisbatda. Katta burchakni toping.",
    options: ["$105°$", "$75°$", "$70°$", "$110°$"],
    answer: "$105°$",
    solution: "$12x = 180° \\Rightarrow x = 15°$; katta: $7 \\cdot 15° = 105°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_076",
    text: "Ikki to'g'ri chiziq kesishganda hosil bo'lgan to'rtta burchakdan ikkitasining yig'indisi $200°$. Bu burchaklar qanday joylashgan?",
    options: ["Teskari (vertikal)", "Qo'shni", "Parallel", "Bir-biriga teng"],
    answer: "Teskari (vertikal)",
    solution: "Qo'shni burchaklar $180°$ beradi. $200° \\neq 180°$, demak ular teskari (vertikal) burchaklar: $\\alpha + \\alpha = 200° \\Rightarrow \\alpha = 100°$.",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_077",
    text: "Ikki to'g'ri chiziq kesishdi. O'tkir burchak o'tmas burchakdan $60°$ ga kichik. O'tkir burchakni toping.",
    options: ["$60°$", "$120°$", "$70°$", "$110°$"],
    answer: "$60°$",
    solution: "$\\alpha + (\\alpha + 60°) = 180° \\Rightarrow 2\\alpha = 120° \\Rightarrow \\alpha = 60°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_078",
    text: "Ikki to'g'ri chiziq kesishdi. Katta burchak kichik burchakdan $100°$ ga katta. Katta burchakni toping.",
    options: ["$140°$", "$40°$", "$130°$", "$120°$"],
    answer: "$140°$",
    solution: "$2\\alpha + 100° = 180° \\Rightarrow \\alpha = 40°$; katta: $40° + 100° = 140°$",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_079",
    text: "Bir nuqtadan $n$ ta nur chiqib, $n$ ta burchak hosil bo'lgan. Burchaklar yig'indisi nechaga teng?",
    options: ["$360°$", "$180°$", "$n \\cdot 90°$", "$n \\cdot 180°$"],
    answer: "$360°$",
    solution: "Bir nuqtadan chiqqan barcha nurlar hosil qilgan burchaklar yig'indisi doim $360°$ ga teng.",
    topic: "Geometriya", difficulty: "O'rtacha",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
  {
    id: "geo_080",
    text: "Ikki to'g'ri chiziq kesishdi. Teskari burchaklardan birining bisektrissasi qo'shni burchakni necha qismga bo'ladi?",
    options: ["Ikkiga: teng qismlarga", "Ikkiga: $\\alpha/2$ va $180°-\\alpha/2$", "Uchga", "Bo'lmaydi"],
    answer: "Ikkiga: $\\alpha/2$ va $180°-\\alpha/2$",
    solution: "Burchak $\\alpha$, uning bisektrissasi $\\alpha/2$ va $\\alpha/2$ ga bo'ladi. Qo'shni burchakka kirib, uni $\\alpha/2$ va $(180°-\\alpha)-\\alpha/2 = 180° - \\dfrac{3\\alpha}{2}$ ga bo'ladi.",
    topic: "Geometriya", difficulty: "Qiyin",
    exam_type: ["DTM", "Milliy Sertifikat", "Maktab"],
  },
];

const { data, error } = await supabase.from("questions").upsert(questions);

if (error) {
  console.error("Xato:", error.message);
} else {
  console.log(`✓ ${questions.length} ta masala muvaffaqiyatli yuklandi!`);
}
